### ISSUE TITLE
could it possible use it with  [tape-watch](https://www.npmjs.com/package/tape-watch)

### ISSUE THREAD

**Issue by HaveF** [Raynos/leaked-handles#1]
Thanks for your repo!

btw, could it possible to use it with  [tape-watch](https://www.npmjs.com/package/tape-watch)?

thanks!

**Comment by Raynos** [comment]
yes ?

I integrated it into `itape` before ( https://github.com/Raynos/itape )

**Comment by HaveF** [comment]
i do suppose *watch is like something unclosed?

Maybe I will try it later.
